CREATE TABLE stock_pool (
  code VARCHAR(6) NOT NULL COMMENT '代码',
  name VARCHAR(10) NULL COMMENT '名称',
  industry VARCHAR(50) NULL COMMENT '细分行业',
  outstanding DECIMAL(12,2) NULL COMMENT '流通股本',
  totalAssets DECIMAL(12,2) NULL COMMENT '总资产(万)',
  fixedAssets DECIMAL(12,2) NULL COMMENT '固定资产',
  liquidAssets DECIMAL(12,2) NULL COMMENT '流动资产',
  totalMarketValue DECIMAL(12,2) NULL COMMENT '总市值',
  outstandMarketValue DECIMAL(12,2) NULL COMMENT '流通市值',
  realMarketValue DECIMAL(12,2) NULL COMMENT '真实流通市值',
  PRIMARY KEY (code)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE pressure_monitor (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  code VARCHAR(6) NOT NULL,
  name VARCHAR(10) NULL,
  open DECIMAL(12,2) NULL,
  pre_close DECIMAL(12,2) NULL,
  price DECIMAL(12,2) NULL,
  high DECIMAL(12,2) NULL,
  low DECIMAL(12,2) NULL,
  sell_price1 DECIMAL(12,2) NULL,
  sell_volume1 DECIMAL(12,0) NULL,
  sell_price2 DECIMAL(12,2) NULL,
  sell_volume2 DECIMAL(12,0) NULL,
  sell_price3 DECIMAL(12,2) NULL,
  sell_volume3 DECIMAL(12,0) NULL,
  sell_price4 DECIMAL(12,2) NULL,
  sell_volume4 DECIMAL(12,0) NULL,
  sell_price5 DECIMAL(12,2) NULL,
  sell_volume5 DECIMAL(12,0) NULL,
  buy_price1 DECIMAL(12,2) NULL,
  buy_volume1 DECIMAL(12,0) NULL,
  buy_price2 DECIMAL(12,2) NULL,
  buy_volume2 DECIMAL(12,0) NULL,
  buy_price3 DECIMAL(12,2) NULL,
  buy_volume3 DECIMAL(12,0) NULL,
  buy_price4 DECIMAL(12,2) NULL,
  buy_volume4 DECIMAL(12,0) NULL,
  buy_price5 DECIMAL(12,2) NULL,
  buy_volume5 DECIMAL(12,0) NULL,
  pressure_date VARCHAR(20) NULL,
  pressure_time VARCHAR(20) NULL,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY pressure_monitor_idx01(code),
  KEY pressure_monitor_idx02(pressure_date),
  KEY pressure_monitor_idx03(create_datetime)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE analysis_results (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  code VARCHAR(6) NOT NULL,
  name VARCHAR(10) NULL,
  change_rate DECIMAL(12,2) NULL,
  price DECIMAL(12,2) NULL,
  amount DECIMAL(12,0) NULL,
  outstandMarketValue DECIMAL(12,2) NULL,
  today_times INT NULL,
  days INT NULL,
  pressure_date VARCHAR(20) NULL,
  pressure_time VARCHAR(20) NULL,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY analysis_results_idx01(code),
  KEY analysis_results_idx02(pressure_date),
  KEY analysis_results_idx03(modified_datetime)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;