CREATE TABLE stock_pool (
  code VARCHAR(6) NOT NULL COMMENT '代码',
  name VARCHAR(10) NULL COMMENT '名称',
  industry VARCHAR(50) NULL COMMENT '细分行业',
  outstanding DECIMAL(12,2) NULL COMMENT '流通股本',
  totalAssets DECIMAL(12,2) NULL COMMENT '总资产(万)',
  fixedAssets DECIMAL(12,2) NULL COMMENT '固定资产',
  liquidAssets DECIMAL(12,2) NULL COMMENT '流动资产',
  totalMarketValue DECIMAL(12,2) NULL COMMENT '总市值',
  outstandMarketValue DECIMAL(12,2) NULL COMMENT '流通市值',
  realMarketValue DECIMAL(12,2) NULL COMMENT '真实流通市值',
  PRIMARY KEY (code));

CREATE TABLE pressure_monitor (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  code VARCHAR(6) NOT NULL,
  name VARCHAR(10) NULL,
  open DECIMAL(12,3) NULL,
  pre_close DECIMAL(12,3) NULL,
  price DECIMAL(12,3) NULL,
  high DECIMAL(12,3) NULL,
  low DECIMAL(12,3) NULL,
  sell_price1 DECIMAL(12,3) NULL,
  sell_amount1 DECIMAL(12,0) NULL,
  sell_price2 DECIMAL(12,3) NULL,
  sell_amount2 DECIMAL(12,0) NULL,
  sell_price3 DECIMAL(12,3) NULL,
  sell_amount3 DECIMAL(12,0) NULL,
  sell_price4 DECIMAL(12,3) NULL,
  sell_amount4 DECIMAL(12,0) NULL,
  sell_price5 DECIMAL(12,3) NULL,
  sell_amount5 DECIMAL(12,0) NULL,
  buy_price1 DECIMAL(12,3) NULL,
  buy_amount1 DECIMAL(12,0) NULL,
  buy_price2 DECIMAL(12,3) NULL,
  buy_amount2 DECIMAL(12,0) NULL,
  buy_price3 DECIMAL(12,3) NULL,
  buy_amount3 DECIMAL(12,0) NULL,
  buy_price4 DECIMAL(12,3) NULL,
  buy_amount4 DECIMAL(12,0) NULL,
  buy_price5 DECIMAL(12,3) NULL,
  buy_amount5 DECIMAL(12,0) NULL,
  datetime VARCHAR(20) NULL,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id));

CREATE TABLE analysis_results (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  code VARCHAR(6) NOT NULL,
  name VARCHAR(10) NULL,
  change_rate DECIMAL(12,3) NULL,
  price DECIMAL(12,3) NULL,
  amount DECIMAL(12,0) NULL,
  outstandMarketValue DECIMAL(12,2) NULL,
  today_times INT NULL,
  days INT NULL,
  datetime VARCHAR(20) NULL,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id));