CREATE TABLE stock_pool (
  code VARCHAR(6) NOT NULL COMMENT '代码',
  name VARCHAR(10) NULL COMMENT '名称',
  industry VARCHAR(50) NULL COMMENT '细分行业',
  outstanding DECIMAL(12,2) NULL COMMENT '流通股本',
  totalAssets DECIMAL(12,2) NULL COMMENT '总资产(万)',
  fixedAssets DECIMAL(12,2) NULL COMMENT '固定资产',
  liquidAssets DECIMAL(12,2) NULL COMMENT '流动资产',
  totalMarketValue DECIMAL(12,2) NULL COMMENT '总市值',
  outstandMarketValue DECIMAL(12,2) NULL COMMENT '流通市值',
  realMarketValue DECIMAL(12,2) NULL COMMENT '真实流通市值',
  PRIMARY KEY (code));

CREATE TABLE pressure_monitor (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  code VARCHAR(16) NOT NULL,
  name VARCHAR(64) NULL,
  sell_price1 VARCHAR(64) NULL,
  sell_amount1 VARCHAR(64) NULL,
  sell_price2 VARCHAR(64) NULL,
  sell_amount2 VARCHAR(64) NULL,
  sell_price3 VARCHAR(64) NULL,
  sell_amount3 VARCHAR(64) NULL,
  sell_price4 VARCHAR(64) NULL,
  sell_amount4 VARCHAR(64) NULL,  
  sell_price5 VARCHAR(64) NULL,
  sell_amount5 VARCHAR(64) NULL,  
  buy_price1 VARCHAR(64) NULL,
  buy_amount1 VARCHAR(64) NULL,
  buy_price2 VARCHAR(64) NULL,
  buy_amount2 VARCHAR(64) NULL,
  buy_price3 VARCHAR(64) NULL,
  buy_amount3 VARCHAR(64) NULL,
  buy_price4 VARCHAR(64) NULL,
  buy_amount4 VARCHAR(64) NULL,  
  buy_price5 VARCHAR(64) NULL,
  buy_amount5 VARCHAR(64) NULL,  
  datetime VARCHAR(64) NULL,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id));

CREATE TABLE analysis_results (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  code VARCHAR(6) NOT NULL,
  name VARCHAR(10) NULL,
  times INT NULL,
  datetime VARCHAR(64) NULL,
  amount DECIMAL(12,0) NULL,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id));